/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/J1swfBP3ZeH
 */
import { storefrontClient } from "clients/storefrontClient"
import { Button } from "components/Button"
import { ChevronIcon } from "components/Icons/ChevronIcon"
import { Label } from "components/Label"
import { RadioGroup, RadioGroupItem } from "components/RadioGroup"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "components/Select"
import { notFound } from "next/navigation"
import { Gallery } from "./Gallery"

export async function ProductView({ slug }) {
  const product = await storefrontClient.getProductByHandle(slug)

  if (!product) {
    return notFound()
  }

  return (
    <main className="container mx-auto px-4 py-8">
      <nav aria-label="Breadcrumb" className="mb-4">
        <ol className="flex items-center space-x-1 text-sm">
          <li>
            <a className="text-gray-600 hover:underline" href="#">
              Home
            </a>
          </li>
          <li>{`>`}</li>
          <li>
            <a className="text-gray-600 hover:underline" href="#">
              Electronics
            </a>
          </li>
          <li>{`>`}</li>
          <li aria-current="page" className="font-medium">
            Product A
          </li>
        </ol>
      </nav>
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
        <Gallery />
        <div>
          <h1 className="mb-2 text-3xl font-bold">Product A</h1>
          <div className="mb-4 flex items-center">
            <StarIcon className="h-5 w-5 text-yellow-400" />
            <StarIcon className="h-5 w-5 text-yellow-400" />
            <StarIcon className="h-5 w-5 text-yellow-400" />
            <StarIcon className="h-5 w-5 text-yellow-400" />
            <span className="ml-2 text-sm text-gray-600">26 Reviews</span>
          </div>
          <p className="mb-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur.
          </p>
          <div className="mb-4 flex items-center space-x-2">
            <span className="h-6 w-6 rounded-full bg-gray-400" />
            <span className="h-6 w-6 rounded-full bg-gray-400" />
            <span className="h-6 w-6 rounded-full bg-red-500" />
          </div>
          <div className="mb-4 text-3xl font-bold">50,99€</div>
          <Button className="w-full">Add to Cart</Button>
        </div>
      </div>
      <section aria-labelledby="also-like-heading" className="mt-16">
        <h2 className="mb-4 text-2xl font-bold" id="also-like-heading">
          You might also like
        </h2>
        <div className="grid grid-cols-2 gap-4 md:grid-cols-5">
          <div>
            <img
              alt="Product B"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <h3 className="mt-2 text-lg font-medium">Product B</h3>
            <p className="mb-2">67,98€</p>
          </div>
          <div>
            <img
              alt="Product C"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <h3 className="mt-2 text-lg font-medium">Product C</h3>
            <p className="mb-2">67,98€</p>
          </div>
          <div>
            <img
              alt="Product D"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <h3 className="mt-2 text-lg font-medium">Product D</h3>
            <p className="mb-2">67,98€</p>
          </div>
          <div>
            <img
              alt="Product E"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <h3 className="mt-2 text-lg font-medium">Product E</h3>
            <p className="mb-2">67,98€</p>
          </div>
          <div className="flex items-center justify-center">
            <button aria-label="Previous product">
              <ChevronIcon className="h-6 w-6" />
            </button>
            <button aria-label="Next product">
              <ChevronIcon className="h-6 w-6" />
            </button>
          </div>
        </div>
      </section>
    </main>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
