name: Check
on:
  push:
    branches: ["main", "master", "develop", "preprod"]
    paths:
      - "starters/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "starters/**"

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      meilisearch: ${{ steps.filter.outputs.meilisearch }}
      algolia: ${{ steps.filter.outputs.algolia }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            shopify-meilisearch:
              - 'starters/shopify-meilisearch/**'
            shopify-algolia:
              - 'starters/shopify-algolia/**'

  build:
    needs: check-changes
    strategy:
      matrix:
        app:
          [
            {
              name: shopify-meilisearch,
              working-directory: ./starters/shopify-meilisearch,
              should-run: needs.check-changes.outputs.shopify-meilisearch,
            },
            {
              name: shopify-algolia,
              working-directory: ./starters/shopify-algolia,
              should-run: needs.check-changes.outputs.shopify-algolia,
            },
          ]
    if: ${{ fromJson(matrix.app.should-run) }}

    environment: Production
    name: Build and Test (${{ matrix.app.name }})
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.app.name }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      SKIP_ENV_VALIDATION: true
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_ACCESS_TOKEN }}
      SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
      MEILISEARCH_ADMIN_KEY: ${{ secrets.MEILISEARCH_ADMIN_KEY }}
      MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
      SHOPIFY_APP_API_SECRET_KEY: ${{ secrets.SHOPIFY_APP_API_SECRET_KEY }}
      REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "Use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ matrix.app.name }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
        working-directory: ${{ matrix.app.working-directory }}

      - name: Licenses check
        run: npx --yes license-checker-rseidelsohn --production --excludePrivatePackages --onlyAllow "MPL-2.0;UNKNOWN;MIT;Apache;AAL;BSD;Artistic;CC0;ISC;ISCL;PostgreSQL License;Public Domain;Unlicense;UPL;W3C;WTFPL;Python;CC-;BlueOak"

      - name: Test
        run: yarn test
        working-directory: ${{ matrix.app.working-directory }}

      - name: Lint
        run: yarn lint
        working-directory: ${{ matrix.app.working-directory }}

      - name: Format
        run: yarn format
        working-directory: ${{ matrix.app.working-directory }}

      - name: Build
        run: yarn build
        working-directory: ${{ matrix.app.working-directory }}
